ConventionMappingApplication/WebUI/Models/ConListViewModel.cs
using BusinessObjects;
using System.Collections.Generic;

namespace WebUI.Models
{
    public class ConListViewModel
    {
        public ConListViewModel()
        {
            Conventions = new List<ConventionViewModel>();
        }

        public List<ConventionViewModel> Conventions { get; set; }
    }
}

ConventionMappingApplication/WebUI/Models/ConventionViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    public class ConventionViewModel
    {
        public int ID { get; set; }

        public int TotalMaps { get; set; }

        [Required, DisplayName("Name*")]
        public string Name { get; set; }

        [Required, DisplayName("Start Date*")]
        public string StartDate { get; set; }

        [Required, DisplayName("End Date*")]
        public string EndDate { get; set; }

        [DisplayName("Description")]
        public string Description { get; set; }

        [Required, DisplayName("Address*")]
        public string Address { get; set; }

        [Required, DisplayName("ZipCode*")]
        public int ZipCode { get; set; }

        [Required, DisplayName("State*")]
        public string State { get; set; }

        [Required, DisplayName("City*")]
        public string City { get; set; }
    }
}

ConventionMappingApplication/WebUI/Models/EventListViewModel.cs
using System.Collections.Generic;

namespace WebUI.Models
{
    public class EventListViewModel
    {
        public EventListViewModel()
        {
            Events = new List<EventViewModel>();
        }

        public List<EventViewModel> Events { get; set; }
    }
}

ConventionMappingApplication/WebUI/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WebUI.Models
{
    public class EventViewModel
    {
        public EventViewModel()
        {
            Rooms = new List<SelectListItem>();
        }

        public int ID { get; set; }
        public int RoomID { get; set; }

        [Required, DisplayName("Name*")]
        public string Name { get; set; }

        [Required, DisplayName("Date*")]
        public string Date { get; set; }

        [Required, DisplayName("Start Time*"), DisplayFormat(ApplyFormatInEditMode = true,
            DataFormatString = "{0:hh:mm tt}"), DataType(DataType.Time)]
        public DateTime StartTime { get; set; }
        public string STime { get; set; }

        [Required, DisplayName("End Time*"), DisplayFormat(ApplyFormatInEditMode = true,
            DataFormatString = "{0:hh:mm tt}"), DataType(DataType.Time)]
        public DateTime EndTime { get; set; }
        public string ETime { get; set; }

        [DisplayName("Description")]
        public string Description { get; set; }

        [DisplayName("Location*")]
        public IEnumerable<SelectListItem> Rooms { get; set; }
    }
}

ConventionMappingApplication/WebUI/Models/RoomViewModel.cs
namespace WebUI.Models
{
    public class RoomViewModel
    {
        public int FloorNumber { get; set; }

        public int TotalFloors { get; set; }
    }
}

ConventionMappingApplication/WebUI/Controllers/ConventionController.cs
using System;
using System.Collections.Generic;
using Services;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessObjects;
using WebUI.Models;
using WebUI.Transformers;

namespace WebUI.Controllers
{
    public partial class ConventionController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IConventionService _conventionService;
        private readonly IRoomService _roomService;
        private readonly IEventTransformer _eventTransformer;
        private readonly IConventionTransformer _conventionTransformer;

        public ConventionController(IEventService eventService, IEventTransformer eventTransformer, IConventionService conventionService, IConventionTransformer conventionTransformer, IRoomService roomService)
        {
            _eventService = eventService;
            _eventTransformer = eventTransformer;
            _conventionService = conventionService;
            _conventionTransformer = conventionTransformer;
            _roomService = roomService;
        }

        [HttpGet]
        public virtual ActionResult Create()
        {
            var model = new ConventionViewModel
            {
                ID = 0
            };
            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Create(ConventionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var convention = _conventionTransformer.TransformToBusinessObject(model);
            Session["conventionId"] = _conventionService.SaveConvention(convention);
            return RedirectToAction(MVC.Convention.Map());
        }

        [HttpGet]
        public virtual ActionResult ConList()
        {
            return View(MVC.Convention.Views.ConList);
        }

        [HttpGet]
        public virtual JsonResult GetConList()
        {
            var cons = _conventionService.GetAllConventions();
            var conventions = cons.Select(con => _conventionTransformer.TransformToViewModel(con)).ToList();
            return Json(conventions, JsonRequestBehavior.AllowGet); 
        }

        [HttpGet]
        public virtual ActionResult Edit(int id)
        {
            var con = _conventionService.GetConventionById(id);
            Session["conventionId"] = con.ID;
            var model = _conventionTransformer.TransformToViewModel(con);

            var maps = _conventionService.GetMapByConventionId(con.ID);

            var totalMaps = 0;
            if (maps.Floor1 != null)
            {
                totalMaps++;
            }
            if (maps.Floor2 != null)
            {
                totalMaps++;
            }
            if (maps.Floor3 != null)
            {
                totalMaps++;
            }

            model.TotalMaps = totalMaps;
            return View(MVC.Convention.Views.Edit, model);
        }

        [HttpPost]
        public virtual ActionResult Edit(ConventionViewModel model)
        {
            var convention = _conventionTransformer.TransformToBusinessObject(model);
            Session["conventionId"] = _conventionService.SaveConvention(convention);
            return RedirectToAction(MVC.Convention.ConList());
        }

        [HttpGet]
        public virtual ActionResult EventList()
        {
            return View(MVC.Convention.Views.EventList);
        }

        [HttpGet]
        public virtual JsonResult GetEventList()
        {
            var eventList = _eventService.GetAllEventsForAConvention((int)Session["conventionId"]);
            var events = eventList.Select(e => _eventTransformer.TrasformToViewModel(e)).ToList();
            return Json(events, JsonRequestBehavior.AllowGet); 
        }

        [HttpGet]
        public virtual ActionResult EditEvent(int id)
        {
            var model = new EventViewModel{ ID = id };
            
            var conEvent = _eventService.GetEventById(id);
            if (conEvent != null)
            {
                model = _eventTransformer.TrasformToViewModel(conEvent);
            }

            model.Rooms = _roomService.GetRoomsForGivenConventionId((int)Session["conventionId"])
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.ID.ToString()
                });

            return View(MVC.Convention.Views.Event, model);
        }

        [HttpPost]
        public virtual ActionResult EditEvent(EventViewModel model)
        {
            var conEvent = _eventTransformer.TrasformToBusinessObject(model);
            _eventService.SaveEvent(conEvent);
            return RedirectToAction(MVC.Convention.EditEvent(0));
        }

        [HttpGet]
        public virtual ActionResult Map()
        {
            var allFloors = _conventionService.GetMapByConventionId((int)Session["conventionId"]);
            return View(allFloors.Floor1 != null);
        }

        [HttpPost]
        public virtual ActionResult Map(HttpPostedFileBase file)
        {
            byte[] map = new byte[file.InputStream.Length];
            file.InputStream.Read(map, 0, map.Length);

            _conventionService.SaveMap((int) Session["conventionId"], map);
            return Json(true);
        }

        [HttpGet]
        public virtual ActionResult FloorMap(int floorNumber)
        {
            var allFloors = _conventionService.GetMapByConventionId((int) Session["conventionId"]);
            byte[] map;
            switch (floorNumber)
            {
                case 2:
                    map = allFloors.Floor2;
                    break;
                case 3:
                    map = allFloors.Floor3;
                    break;
                default:
                    map = allFloors.Floor1;
                    break;
            }
            return File(map, "image/jpeg");
        }

        [HttpGet]
        public virtual ActionResult Rooms(int? floorNumber)
        {
            if (floorNumber == null)
            {
                floorNumber = 1;
            }

            int totalFloors = 0;
            var allFloors = _conventionService.GetMapByConventionId((int) Session["conventionId"]);
            if (allFloors.Floor1 != null)
            {
                totalFloors++;
            }
            if (allFloors.Floor2 != null)
            {
                totalFloors++;
            }
            if (allFloors.Floor3 != null)
            {
                totalFloors++;
            }

            var model = new RoomViewModel
            {
                FloorNumber = (int)floorNumber,
                TotalFloors = totalFloors
            };
            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Rooms(int floorNumber, List<Room> rooms)
        {
            if (rooms != null)
            {
                _roomService.SaveRooms((int)Session["conventionId"], floorNumber, rooms);
            }
            return Json(true);
        }
    }
}

ConventionMappingApplication/WebUI/Views/Convention/ConList.cshtml
@{
    ViewBag.Title = "Select a Convention to Edit";
}
<div class="row">
    <div class="col-md-8">
        <h2>@ViewBag.Title</h2>
        <p>Select a Convention from the list below or create a new one.</p>
    </div>
    <div class="col-md-4">
        <div class="text-right marginTopBottom">
            <a href="@Url.Action(MVC.Convention.Create())" class="btn btn-default mainBtn">+ Add Convention</a>
        </div>
    </div>
</div>
<div class="row rowPadTop">
    <div class="col-md-12">
        <table id="conTable" class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>State</th>
                    <th>Zip Code</th>
                    <th>Description</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>State</th>
                    <th>Zip Code</th>
                    <th>Description</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#conTable').DataTable({
                "ajax": {
                    "url": "../Convention/GetConList",
                    "dataSrc": ""
                },
                "columns": [
                {
                    "data": "ID",
                    "visible": false,
                    "searchable": false
                },
                { "data": "Name" },
                { "data": "Address" },
                { "data": "State" },
                { "data": "ZipCode" },
                { "data": "Description" },
                { "data": "StartDate" },
                { "data": "EndDate" }]
            });

            $('#conTable tbody').on('click', 'tr', function () {
                var rowId = table.row(this).data().ID;
                var url = '@Url.Action("Edit", "Convention", new { id = "__id__" })';
                window.location.href = url.replace('__id__', rowId);
            });
        });
    </script>
}

ConventionMappingApplication/WebUI/Views/Convention/Create.cshtml
@using WebUI.Models
@model ConventionViewModel

@{
    ViewBag.Title = "Create a Convention";
}
@section scripts{
    <script type="text/javascript">
        $("form").validate({
            rules: {
                EndDate: { greaterThan: "#StartDate" }
            }
        });
    </script>
}
<h2>@ViewBag.Title</h2>
@Html.HiddenFor(m => m.ID)

<div class="row">
    <div class="col-md-8">
        <section id="createConForm">
            @using (Html.BeginForm(MVC.Convention.Create(), FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <h4>Fill out the following fields to create a convention.</h4>
                <hr />
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.City, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.State, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ZipCode, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.ZipCode, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control datepicker" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.EndDate, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.EndDate, new { @class = "form-control datepicker" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

ConventionMappingApplication/WebUI/Views/Convention/EventList.cshtml
@{
    ViewBag.Title = "Select an Event to Edit";
}

<div class="row">
    <div class="col-md-8">
        <h2>@ViewBag.Title</h2>
    </div>
    <div class="col-md-4">
        <div class="text-right marginTopBottom">
            <a href="@Url.Action(MVC.Convention.EditEvent(0))" class="btn btn-default mainBtn">+ Add Event</a>
        </div>
    </div>
</div>
<div class="row rowPadTop">
    <div class="col-md-12">
        <table id="eventTable" class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Date</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#eventTable').DataTable({
                "ajax": {
                    "url": "../Convention/GetEventList",
                    "dataSrc": ""
                },
                "columns": [
                {
                    "data": "ID",
                    "visible": false,
                    "searchable": false
                },
                { "data": "Name" },
                { "data": "Description" },
                { "data": "STime" },
                { "data": "ETime" },
                { "data": "Date" }]
            });

            $('#eventTable tbody').on('click', 'tr', function () {
                var rowId = table.row(this).data().ID;
                var url = '@Url.Action("EditEvent", "Convention", new { id = "__id__" })';
                window.location.href = url.replace('__id__', rowId);
            });
        });
    </script>
}

ConventionMappingApplication/WebUI/Views/Convention/Map.cshtml
@model bool

@{
    ViewBag.Title = "Upload a Map";
}
@section scripts {
    <script type="text/javascript">
        var hasMaps = @Json.Encode(Model);
        if (hasMaps) {
            $("#nextBtn").removeClass("hidden");
        }
        Dropzone.options.mapUpload = {
            maxFiles: 3,
            accept: function(file, done) {
                toastr.success('Image uploaded!', 'Success');
                if (!hasMaps) {
                    $("#nextBtn").removeClass("hidden");
                }
                done();
            },
            init: function() {
                this.on("maxfilesexceeded",
                    function(file) {
                        toastr.error('No more maps can be uploaded to this convention!', 'Error');
                    });
            }
        };
    </script>
}
@section styles {
    <style>
        .roomIconBox {
            text-align: center;
            border: solid black 1px;
            padding: 10px 0px;
        }
    </style>
}

<h2>@ViewBag.Title</h2>
<p>Upload the Convention Maps representing the different floors starting with the 1st. Up to 3 floors total can be added.</p>
<p>If at least one floor has been added, and no more are required, skip this step.</p>
<div style="margin-bottom: 25px" class="row">
    <div class="col-md-8">
        <section id="mapForm">
            @using (Html.BeginForm(MVC.Convention.Map(), FormMethod.Post, new { id = "mapUpload", @class = "form-horizontal dropzone", role = "form"}))
            {
            }
        </section>
    </div>
    <div class="col-md-4 text-right">
        <input id="nextBtn" type="button" value="Next" class="btn btn-default hidden" onclick="location.href='@Url.Action("Rooms", "Convention")'" />
    </div>
</div>

ConventionMappingApplication/WebUI/Views/Convention/Rooms.cshtml
@using WebUI.Models
@model RoomViewModel

@{
    ViewBag.Title = "Add Rooms";
}
@section scripts {
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        var newCoords = [];
        var roomNum = 1;
        $("#map").droppable({
            accept: '#mapIcon',
            drop: function (event, ui) {
                var $clone = ui.helper.clone();
                if (!$clone.is('.insideContainer')) {
                    $(this).append($clone.attr("id", 'room' + roomNum));
                    roomNum += 1;

                    var currentLocation = $clone;
                    var thisPos = currentLocation.position();
                    var parentPos = currentLocation.parent().position();

                    var parentSizeModifier = 1000 / currentLocation.parent().width();

                    var roomId = $clone[0].id;
                    var x = parseInt(((currentLocation.width() / 2) + thisPos.left - parentPos.left - 15) * parentSizeModifier);
                    var y = parseInt((currentLocation.height() + thisPos.top - parentPos.top) * parentSizeModifier);

                    var found = false;
                    if (roomId.includes("room")) {
                        for (var i in newCoords) {
                            if (newCoords[i].JavascriptID === roomId) {
                                newCoords[i].XCoordinate = x;
                                newCoords[i].YCoordinate = y;

                                found = true;
                                break;
                            }
                        }
                        if (!found) {
                            newCoords.push({
                                JavascriptID: roomId,
                                XCoordinate: x,
                                YCoordinate: y
                            });
                        }
                    }

                    $(this).append($clone.addClass('insideContainer').draggable({
                        containment: '#map',
                        stop: function() {
                            var currentLocation = $(this);
                            var thisPos = currentLocation.position();
                            var parentPos = currentLocation.parent().position();

                            var parentSizeModifier = 1000 / currentLocation.parent().width();

                            var roomId = this.id;
                            var x = parseInt(((currentLocation.width() / 2) + thisPos.left - parentPos.left - 15) * parentSizeModifier);
                            var y = parseInt((currentLocation.height() + thisPos.top - parentPos.top) * parentSizeModifier);

                            var found = false;
                            if (roomId.includes("room")) {
                                for (var i in newCoords) {
                                    if (newCoords[i].JavascriptID === roomId) {
                                        newCoords[i].XCoordinate = x;
                                        newCoords[i].YCoordinate = y;

                                        found = true;
                                        break;
                                    }
                                }
                                if (!found) {
                                    newCoords.push({
                                        JavascriptID: roomId,
                                        XCoordinate: x,
                                        YCoordinate: y
                                    });
                                }
                            }
                        }
                    }));
                }
            }
        });
        $(".drag").draggable({
            appendTo: '#map',
            helper: 'clone'
        });

        $("#nextBtn, #prevBtn").click(function() {
            saveCoords();
        });

        function saveCoords() {
            $.ajax({
                type: "POST",
                url: "/Convention/Rooms/",
                data: {floorNumber: @Model.FloorNumber, rooms: newCoords},
                success: function() {
                    toastr.success('The changes were saved!', 'Success');
                }
            });
        }
    </script>
}
@section styles {
    <style>
        .roomIconBox {
            text-align: center;
            border: solid black 1px;
            padding: 10px 0;
        }

        #mapIcon {
            margin-bottom: 10px;
        }

        #prevBtn {
            padding: 8px;
            margin: 5px 0;
        }

        #nextBtn {
            margin-bottom: 5px;
        }
    </style>
}

<h2>@ViewBag.Title</h2>
<p>Drag and drop the blue icon on the side to the location of the rooms on the uploaded map.</p>
<p>To finish and exit click the "Submit" button.</p>

<div class="row">
    <div class="col-md-12">
        <section id="roomForm">
            @using (Html.BeginForm(MVC.Convention.Rooms(), FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="row">
                    <div id="map" class="col-md-11">
                        <img style="width:100%" src="@Url.Action("FloorMap", "Convention", new {floorNumber = Model.FloorNumber})" />
                    </div>
                    <div class="col-md-1 roomIconBox">
                        <div class="row">
                            <div class="col-md-12">
                                <img id="mapIcon" class="drag" style="height: 40px; width: 25px;" src="@Links.Content.Images.mapIcon_png" />
                            </div>
                        </div>
                        @if (Model.TotalFloors - Model.FloorNumber != 0 && (Model.TotalFloors - Model.FloorNumber == 1 || Model.FloorNumber != 3))
                        {
                            <div class="row">
                                <div class="col-md-12">
                                    <input id="nextBtn" type="button" value="Next" class="btn btn-default" onclick="location.href='@Url.Action("Rooms", "Convention", new { floorNumber = Model.FloorNumber + 1 })'" />
                                </div>
                            </div>
                        }
                        @if (Model.FloorNumber != 1)
                        {
                            <div class="row">
                                <div class="col-md-12">
                                    <input id="prevBtn" type="button" value="Previous" class="btn btn-default" onclick="location.href='@Url.Action("Rooms", "Convention", new { floorNumber = Model.FloorNumber - 1 })'" />
                                </div>
                            </div>
                        }
                        <div class="row">
                            <div class="col-md-12">
                                <a href="@Url.Action(MVC.Convention.EventList())" style="margin: 5px 0;" class="btn btn-default mainBtn" onclick="saveCoords()">Submit</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </section>
    </div>
</div>